// src/pages/ContractDetails.js
export const contractDetails = {
  '1': {
    title: 'Contrat de Travail à Durée Déterminée',
    author: 'Société ABC',
    usage: 5,
    duration: '12 mois',
    description: 'Contrat de travail temporaire pour une durée déterminée, avec possibilité de renouvellement.',
    applicableLaws: ['Code du Travail', 'Loi sur les Contrats Temporaires'],
    image: 'https://res.cloudinary.com/db2lbrqix/image/upload/v1716211952/Capture_d_e%CC%81cran_2024-05-20_a%CC%80_14.32.27_rhbbze.png',
  },
  '2': {
    title: 'Contrat de Travail à Durée Indéterminée',
    author: 'Société XYZ',
    usage: 10,
    duration: 'Indéterminée',
    description: 'Contrat de travail à durée indéterminée, incluant une période d’essai de 6 mois.',
    applicableLaws: ['Code du Travail', 'Loi sur les Contrats de Travail'],
    image: 'https://res.cloudinary.com/db2lbrqix/image/upload/v1716211952/Capture_d_e%CC%81cran_2024-05-20_a%CC%80_14.32.27_rhbbze.png',
  },
  '3': {
    title: 'Contrat de Travail Temporaire',
    author: 'Société LMN',
    usage: 3,
    duration: '6 mois',
    description: 'Contrat temporaire pour des missions spécifiques, avec des clauses de fin de mission.',
    applicableLaws: ['Code du Travail', 'Loi sur les Contrats Temporaires'],
    image: 'https://via.placeholder.com/150x200?text=Contrat+3',
  },
  '4': {
    title: 'Attestation de Présence',
    author: 'Société DEF',
    usage: 7,
    duration: 'N/A',
    description: 'Attestation prouvant la présence d’un employé au sein de l’entreprise durant une période spécifique.',
    applicableLaws: ['Code du Travail', 'Loi sur les Attestations'],
    image: 'https://via.placeholder.com/150x200?text=Attestation+1',
  },
  '5': {
    title: 'Attestation de Formation',
    author: 'Société GHI',
    usage: 4,
    duration: 'N/A',
    description: 'Attestation confirmant la participation d’un employé à une formation professionnelle.',
    applicableLaws: ['Code du Travail', 'Loi sur les Formations'],
    image: 'https://via.placeholder.com/150x200?text=Attestation+2',
  },
  '6': {
    title: 'Attestation de Congés',
    author: 'Société JKL',
    usage: 6,
    duration: 'N/A',
    description: 'Attestation indiquant les congés pris par un employé, qu’ils soient payés ou non.',
    applicableLaws: ['Code du Travail', 'Loi sur les Congés'],
    image: 'https://via.placeholder.com/150x200?text=Attestation+3',
  },
};
